#!/usr/bin/env bash

set -o errexit # Abort on nonzero exit code.
set -o nounset # Abort on unbound variable.
set -o pipefail # Don't hide errors within pipes.

for user in /home/*; do
    rm -rf "/home/${user}/.config/bashpass"
done
