name: DEB Build BashPass
on:
  push:
    paths:
      - "bashpass/**"
  pull_request:
    paths:
      - "bashpass/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build BashPass DEB package
      id: deb
      run: |
        cd bashpass/ || exit 1
        git clone https://github.com/AntonVanAssche/BashPass.git
        cd BashPass && git checkout $(git tag | tail -n 1) && cd ../
        bash build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: deb
        path: bashpass/bashpass_3.2_all.deb

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deb

      - uses: AntonVanAssche/yank-packagecloud@v1.0
        continue-on-error: true
        with:
          PACKAGE-NAME: bashpass_3.2_all.deb
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: ubuntu/lunar/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: bashpass_3.2_all.deb
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: ubuntu/lunar/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: AntonVanAssche/yank-packagecloud@v1.0
        continue-on-error: true
        with:
          PACKAGE-NAME: bashpass_3.2_all.deb
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: ubuntu/jammy/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

      - uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: bashpass_3.2_all.deb
          PACKAGECLOUD-USERNAME: AntonVanAssche
          PACKAGECLOUD-REPO: bashpass
          PACKAGECLOUD-DISTRIB: ubuntu/jammy/
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
